name: PyTorch Session 1
on: [push]

jobs:
  torch-basics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          pip install torch torchvision pillow requests

      - name: Run Tensor Lab
        run: python clase23_generador.py
